=== condenser-team/condenser-registry/schema/root/index.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "@context": {
      "type": "string",
      "minLength": 1
    },
    "@type": {
      "type": "string",
      "minLength": 1
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "version": {
      "type": "string",
      "minLength": 1
    },
    "hasPart": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@id": {
            "type": "string",
            "format": "uri"
          },
          "@type": {
            "type": "string",
            "const": "ItemList"
          },
          "name": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "@id",
          "@type"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "@context",
    "@type",
    "@id",
    "name",
    "version",
    "hasPart"
  ],
  "additionalProperties": false,
  "$id": "https://condenser-team.github.io/condenser-registry/schema/root"
}

=== condenser-team/condenser-registry/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/root",
  "@context": "https://schema.org/",
  "@type": "DataCatalog",
  "@id": "https://condenser-team.github.io/condenser-registry",
  "name": "Static API JSON Schema",
  "version": "0.1.0",
  "hasPart": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/authors",
      "@type": "ItemList",
      "name": "authors"
    },
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins"
    },
    {
      "@id": "https://condenser-team.github.io/condenser-registry/authors/search",
      "@type": "ItemList",
      "name": "authors search"
    },
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins/search",
      "@type": "ItemList",
      "name": "plugins search"
    }
  ]
}
