=== condenser-team/condenser-registry/schema/plugins/versions/index.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "@context": {
      "type": "string"
    },
    "@type": {
      "type": "string",
      "const": "SoftwareApplication"
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "datePublished": {
      "type": "string"
    },
    "releaseNotes": {
      "type": "string"
    },
    "isPartOf": {
      "type": "object",
      "properties": {
        "@id": {
          "type": "string",
          "format": "uri"
        },
        "@type": {
          "type": "string",
          "const": "SoftwareApplication"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "@id",
        "@type"
      ],
      "additionalProperties": false
    },
    "associatedMedia": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@type": {
            "type": "string",
            "const": "MediaObject"
          },
          "name": {
            "type": "string"
          },
          "contentSize": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "sha256": {
            "type": "string",
            "pattern": "^[a-f0-9]{64}$"
          },
          "contentUrl": {
            "type": "string",
            "format": "uri"
          },
          "encodingFormat": {
            "type": "string"
          },
          "license": {
            "type": "string",
            "format": "uri"
          },
          "operatingSystem": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "processorRequirements": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "@type",
          "name",
          "contentUrl",
          "encodingFormat",
          "license"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "@context",
    "@type",
    "@id",
    "name",
    "version",
    "datePublished",
    "releaseNotes",
    "isPartOf",
    "associatedMedia"
  ],
  "additionalProperties": false,
  "$id": "https://condenser-team.github.io/condenser-registry/schema/plugins/versions"
}

=== condenser-team/condenser-registry/plugins/example-plugin/versions/latest/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/plugins/versions",
  "@context": "https://schema.org/",
  "@type": "SoftwareApplication",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/example-plugin/versions/1.0.0",
  "name": "Example Plugin 1.0.0",
  "version": "1.0.0",
  "datePublished": "2026-05-29",
  "releaseNotes": "First public prototype release.",
  "isPartOf": {
    "@id": "https://condenser-team.github.io/condenser-registry/plugins/example-plugin",
    "@type": "SoftwareApplication",
    "name": "Example Plugin"
  },
  "associatedMedia": [
    {
      "@type": "MediaObject",
      "name": "Example Plugin v1.0.0",
      "encodingFormat": "application/zip",
      "license": "https://spdx.org/licenses/MIT.html",
      "operatingSystem": [
        "linux",
        "macos",
        "windows"
      ],
      "processorRequirements": [
        "x86_64",
        "arm64"
      ],
      "contentSize": 44,
      "sha256": "a2d40a411a2036e8f8caccc3bbc1ab21b6abaa78b5c721095404d2f9f23fec84",
      "contentUrl": "https://condenser-team.github.io/condenser-registry/plugins/example-plugin/versions/1.0.0/assets/example-plugin-1.0.0.zip"
    }
  ]
}

=== condenser-team/condenser-registry/plugins/condenser-plugin/versions/0.4.0/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/plugins/versions",
  "@context": "https://schema.org/",
  "@type": "SoftwareApplication",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin/versions/0.4.0",
  "name": "Condenser Plugin 0.4.0",
  "version": "0.4.0",
  "datePublished": "2026-05-29",
  "releaseNotes": "Testing plugin",
  "isPartOf": {
    "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
    "@type": "SoftwareApplication",
    "name": "Condenser Plugin"
  },
  "associatedMedia": [
    {
      "@type": "MediaObject",
      "name": "condenser-plugin 0.4.0",
      "contentUrl": "https://github.com/condenser-team/condenser-plugin/releases/download/v0.4.0/condenser-plugin-0.4.0.zip",
      "encodingFormat": "application/zip",
      "license": "https://spdx.org/licenses/MIT.html",
      "sha256": "dfd2f0f885f30278b6ef1114a2ceb80f78cd6b8fa1112e7cccbee2e690f0d670",
      "operatingSystem": [
        "linux",
        "macos",
        "windows"
      ],
      "processorRequirements": [
        "x86_64",
        "arm64"
      ]
    }
  ]
}
