=== condenser-team/condenser-registry/schema/version/index.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "@context": {
      "type": "string",
      "minLength": 1
    },
    "@type": {
      "type": "string",
      "minLength": 1
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "about": {
      "minItems": 1,
      "maxItems": 1,
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@id": {
            "type": "string",
            "format": "uri"
          },
          "@type": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "@id",
          "@type"
        ],
        "additionalProperties": false
      }
    },
    "itemListElement": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@type": {
            "type": "string",
            "const": "ListItem"
          },
          "item": {
            "type": "object",
            "properties": {
              "@id": {
                "type": "string",
                "format": "uri"
              },
              "@type": {
                "type": "string",
                "minLength": 1
              },
              "name": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "@id",
              "@type"
            ],
            "additionalProperties": false
          }
        },
        "required": [
          "@type",
          "item"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "@context",
    "@type",
    "@id",
    "name",
    "about",
    "itemListElement"
  ],
  "additionalProperties": false,
  "$id": "https://condenser-team.github.io/condenser-registry/schema/version"
}

=== condenser-team/condenser-registry/plugins/example-plugin/versions/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/version",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/example-plugin/versions",
  "name": "example-plugin versions",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins/example-plugin",
      "@type": "SoftwareApplication",
      "name": "Example Plugin"
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/example-plugin/versions/1.0.0",
        "@type": "SoftwareApplication",
        "name": "Example Plugin 1.0.0"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/condenser-plugin/versions/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/version",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin/versions",
  "name": "condenser-plugin versions",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
      "@type": "SoftwareApplication",
      "name": "Example Plugin"
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin/versions/0.4.0",
        "@type": "SoftwareApplication",
        "name": "Example Plugin 0.4.0"
      }
    }
  ]
}
