=== condenser-team/condenser-registry/schema/search-value/index.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "@context": {
      "type": "string",
      "minLength": 1
    },
    "@type": {
      "type": "string",
      "minLength": 1
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "about": {
      "minItems": 1,
      "maxItems": 2,
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "@id": {
                "type": "string",
                "format": "uri"
              },
              "@type": {
                "type": "string",
                "const": "ItemList"
              },
              "name": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "@id",
              "@type"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "const": "DefinedTerm"
              },
              "name": {
                "type": "string",
                "minLength": 1
              },
              "inDefinedTermSet": {
                "type": "object",
                "properties": {
                  "@id": {
                    "type": "string",
                    "format": "uri"
                  }
                },
                "required": [
                  "@id"
                ],
                "additionalProperties": false
              }
            },
            "required": [
              "@type",
              "name"
            ],
            "additionalProperties": false
          }
        ]
      }
    },
    "itemListElement": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@type": {
            "type": "string",
            "const": "ListItem"
          },
          "item": {
            "type": "object",
            "properties": {
              "@id": {
                "type": "string",
                "format": "uri"
              },
              "@type": {
                "type": "string",
                "minLength": 1
              },
              "name": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "@id",
              "@type"
            ],
            "additionalProperties": false
          }
        },
        "required": [
          "@type",
          "item"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "@context",
    "@type",
    "@id",
    "name",
    "about",
    "itemListElement"
  ],
  "additionalProperties": false,
  "$id": "https://condenser-team.github.io/condenser-registry/schema/search-value"
}

=== condenser-team/condenser-registry/authors/search/name/nser/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name/nser",
  "name": "authors name nser",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/authors",
      "@type": "ItemList",
      "name": "authors collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "nser",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/condenser-team",
        "@type": "Organization",
        "name": "Condenser Team"
      }
    }
  ]
}

=== condenser-team/condenser-registry/authors/search/name/te/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name/te",
  "name": "authors name te",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/authors",
      "@type": "ItemList",
      "name": "authors collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "te",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/condenser-team",
        "@type": "Organization",
        "name": "Condenser Team"
      }
    }
  ]
}

=== condenser-team/condenser-registry/authors/search/name/den/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name/den",
  "name": "authors name den",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/authors",
      "@type": "ItemList",
      "name": "authors collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "den",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/condenser-team",
        "@type": "Organization",
        "name": "Condenser Team"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/onde/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/onde",
  "name": "plugins name onde",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "onde",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
        "@type": "SoftwareApplication",
        "name": "Condenser Plugin"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/ampl/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/ampl",
  "name": "plugins name ampl",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "ampl",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/example-plugin",
        "@type": "SoftwareApplication",
        "name": "Example Plugin"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/ug/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/ug",
  "name": "plugins name ug",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "ug",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
        "@type": "SoftwareApplication",
        "name": "Condenser Plugin"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/dens/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/dens",
  "name": "plugins name dens",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "dens",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
        "@type": "SoftwareApplication",
        "name": "Condenser Plugin"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/nser/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/nser",
  "name": "plugins name nser",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "nser",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
        "@type": "SoftwareApplication",
        "name": "Condenser Plugin"
      }
    }
  ]
}
