=== condenser-team/condenser-registry/schema/search-value/index.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "@context": {
      "type": "string",
      "minLength": 1
    },
    "@type": {
      "type": "string",
      "minLength": 1
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "about": {
      "minItems": 1,
      "maxItems": 2,
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "@id": {
                "type": "string",
                "format": "uri"
              },
              "@type": {
                "type": "string",
                "const": "ItemList"
              },
              "name": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "@id",
              "@type"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "const": "DefinedTerm"
              },
              "name": {
                "type": "string",
                "minLength": 1
              },
              "inDefinedTermSet": {
                "type": "object",
                "properties": {
                  "@id": {
                    "type": "string",
                    "format": "uri"
                  }
                },
                "required": [
                  "@id"
                ],
                "additionalProperties": false
              }
            },
            "required": [
              "@type",
              "name"
            ],
            "additionalProperties": false
          }
        ]
      }
    },
    "itemListElement": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@type": {
            "type": "string",
            "const": "ListItem"
          },
          "item": {
            "type": "object",
            "properties": {
              "@id": {
                "type": "string",
                "format": "uri"
              },
              "@type": {
                "type": "string",
                "minLength": 1
              },
              "name": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "@id",
              "@type"
            ],
            "additionalProperties": false
          }
        },
        "required": [
          "@type",
          "item"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "@context",
    "@type",
    "@id",
    "name",
    "about",
    "itemListElement"
  ],
  "additionalProperties": false,
  "$id": "https://condenser-team.github.io/condenser-registry/schema/search-value"
}

=== condenser-team/condenser-registry/authors/search/name/ns/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name/ns",
  "name": "authors name ns",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/authors",
      "@type": "ItemList",
      "name": "authors collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "ns",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/condenser-team",
        "@type": "Organization",
        "name": "Condenser Team"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/con/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/con",
  "name": "plugins name con",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "con",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
        "@type": "SoftwareApplication",
        "name": "Condenser Plugin"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/er/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/er",
  "name": "plugins name er",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "er",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
        "@type": "SoftwareApplication",
        "name": "Condenser Plugin"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/u/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/u",
  "name": "plugins name u",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "u",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
        "@type": "SoftwareApplication",
        "name": "Example Plugin"
      }
    }
  ]
}

=== condenser-team/condenser-registry/authors/search/name/on/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name/on",
  "name": "authors name on",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/authors",
      "@type": "ItemList",
      "name": "authors collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "on",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/authors/condenser-team",
        "@type": "Organization",
        "name": "Condenser Team"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/ple/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/ple",
  "name": "plugins name ple",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "ple",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/example-plugin",
        "@type": "SoftwareApplication",
        "name": "Example Plugin"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/xamp/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/xamp",
  "name": "plugins name xamp",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "xamp",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
        "@type": "SoftwareApplication",
        "name": "Example Plugin"
      }
    }
  ]
}

=== condenser-team/condenser-registry/plugins/search/name/exam/index.json
{
  "$schema": "https://condenser-team.github.io/condenser-registry/schema/search-value",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name/exam",
  "name": "plugins name exam",
  "about": [
    {
      "@id": "https://condenser-team.github.io/condenser-registry/plugins",
      "@type": "ItemList",
      "name": "plugins collection"
    },
    {
      "@type": "DefinedTerm",
      "name": "exam",
      "inDefinedTermSet": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/search/name"
      }
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://condenser-team.github.io/condenser-registry/plugins/condenser-plugin",
        "@type": "SoftwareApplication",
        "name": "Example Plugin"
      }
    }
  ]
}
